name: ImGUI Notepad (Windows)

on:
  push:
    tags:
      - 'imgui_application-*'
    branches: [ "imgui_application" ]

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: |
          build
        key: ${{ runner.os }}-cmake-${{ hashFiles('myAppImGUI/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Configure CMake
      run: cmake -S myAppImGUI -B build -G "Visual Studio 17 2022"

    - name: Build project
      run: cmake --build build --config Release

    - name: Get commit message
      id: commit_message
      run: echo "message=$(git log -1 --pretty=format:%s)" >> $env:GITHUB_OUTPUT

    - name: List build output
      run: dir build\Release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: "imgui_notepad_application"
        body: |
          • Commit: ${{ github.sha }}
          • Message: ${{ github.event.head_commit.message }}
        files: build/Release/MyAppImGUI.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
