name: ImGUI Notepad (Windows)

on:
  push:
    tags:
      - 'ImGUI-Notepad-*'
    branches:
      - imgui_application

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S myAppImGUI -B build -G "Visual Studio 17 2022"

    - name: Build project
      run: cmake --build build --config Release

    - name: Get commit message
      id: commit_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Debug commit message
      run: echo "${{ steps.commit_message.outputs.message }}"

    - name: Check if file exists
      run: dir ./build/Release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Commit message:
          ${{ steps.commit_message.outputs.message }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        files: ./build/Release/MyAppImGUI.exe
